import './styles/globals.css'
import Head from 'next/head';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description}/>
        <link rel='icon' href='/public/favicon.png' />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
